items:
  - icon: lucide:settings-2
    to: /settings/preferences
    label: Preferences
  - icon: lucide:user
    to: /settings/profile
    label: Profile
  - icon: lucide:message-square-dot
    to: /settings/notifications
    label: Notifications
  - icon: lucide:user-key
    to: /settings/security
    label: Security and access
